language: cpp
compiler:  
    - gcc
dist: trusty

addons:
  apt:
    packages: libboost-all-dev

install:
# cppcheck
- sudo apt-get install -qq cppcheck

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script:
- make
- cppcheck --quiet --error-exitcode=1 .  